### ISSUE TITLE
Add functionality to specify namespace for avro conversion via payload

### ISSUE THREAD

**Issue by Blitzableiter** [deepshore/avro-converter-backend#4]
currently all converted AVROs contain the namespace "de.deepshore.kafka".
It should be possible to specify an override via payload

**Comment by selamanse** [comment]
@Blitzableiter I have posted a working solution in #6 can you please have a look?

**Comment by Blitzableiter** [comment]
@selamanse thanks for your PR! I've just merged it into main.
